import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { setTimeout as delay } from 'node:timers/promises';
import { create,freePort,ready,service,subscribe,until } from './helpers.js';
import { AgentFakeModel,happy } from './agent-model.js';
import type { AgentRun,AgentStep } from '@repropath/agent-protocol';
import type { ActionRecord } from '@repropath/protocol';
test('M2 production Agent Host → Control → recorded Chromium', {timeout:120000},async t=>{
  const wp=await freePort(),cp=await freePort(),ap=await freePort();const base=`http://127.0.0.1:${cp}`;const fake=new AgentFakeModel();const modelURL=await fake.start();
  const worker=service('apps/browser-worker/src/index.ts',{WORKER_PORT:String(wp),REPROPATH_AUTH_FILE:''});
  const control=service('apps/control/src/index.ts',{CONTROL_PORT:String(cp),WORKER_URL:`ws://127.0.0.1:${wp}/worker`});
  let host=service('apps/agent-host/src/index.ts',{AGENT_HOST_PORT:String(ap),AGENT_CONTROL_URL:`ws://127.0.0.1:${cp}/agent-host`,REPROPATH_AGENT_BASE_URL:modelURL,REPROPATH_AGENT_API_KEY:'FIXTURE_AGENT_API_KEY',REPROPATH_AGENT_MODEL:'fixture'});
  t.after(async()=>{await host.stop();await control.stop();await worker.stop();await fake.close();});await ready(base,true);
  await until(async()=>((await(await fetch(`${base}/health`)).json()) as {modelAvailable:boolean}).modelAvailable,'host ready');
  const session=await create(base,`${base}/test-page/agent`);const stream=await subscribe(base,session.id);t.after(()=>stream.socket.close());await until(()=>stream.states.at(-1)?.status==='running','browser');
  const getActions=async()=>await(await fetch(`${base}/sessions/${session.id}/actions`)).json() as ActionRecord[];
  const start=async()=>{const response=await fetch(`${base}/sessions/${session.id}/agent-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:'检查登录按钮提交后是否出现异常。'})});assert.equal(response.status,201,await response.clone().text());return await response.json() as AgentRun;};
  const get=async(id:string)=>await(await fetch(`${base}/sessions/${session.id}/agent-runs/${id}`)).json() as {run:AgentRun;steps:AgentStep[]};
  const terminal=async(id:string)=>{await until(async()=>['completed','failed','stopped'].includes((await get(id)).run.status),'run terminal',20000);return get(id);};
  await t.test('real happy path, Evidence and correlated deterministic Finding',async()=>{
    const run=await start();const result=await terminal(run.id);assert.equal(result.run.status,'completed',JSON.stringify(result));assert.equal(result.run.finishReason,'goal_reached');assert.equal(result.steps.length,4);
    const actions=await getActions();assert.equal(actions.length,1);const action=actions[0]!;assert.equal(action.actor,'agent');assert.equal(action.kind,'click');assert.equal(action.evidenceStatus,'complete');
    for(const phase of [action.before,action.after])for(const artifact of [phase?.screenshot,phase?.dom]){assert.ok(artifact);assert.equal((await fetch(`${base}/artifacts/${artifact.id}`)).status,200);}
    const signals=await(await fetch(`${base}/sessions/${session.id}/signals`)).json();assert.ok(signals.signals.some((s:{kind:string;actionId:string})=>s.kind==='HTTP_5XX'&&s.actionId===action.id));
    assert.match(JSON.stringify(fake.requests),/HTTP_5XX/);assert.doesNotMatch(JSON.stringify(fake.requests),/PRIVATE_PASSWORD|INITIAL_PRIVATE_VALUE|PRIVATE_TEXTAREA|outerHTML/);assert.ok(stream.frames.length>0);
  });
  await t.test('one model turn cannot execute click click finish',async()=>{fake.reset(o=>({calls:[{name:'click',args:{observationId:o.id,elementRef:o.elements.find(e=>e.name==='Login')!.ref}},{name:'click',args:{observationId:o.id,elementRef:'E1'}},{name:'finish',args:{summary:'bad'}}]}));const before=(await getActions()).length;const r=await terminal((await start()).id);await delay(500);assert.ok((await getActions()).length-before<=1);assert.equal(r.run.errorCode,'ONE_TOOL_PER_TURN');});
  await t.test('policy / unknown tools / invalid schema',async()=>{
    for(const name of ['delete_database','click','navigate']){fake.reset(o=>name==='delete_database'?{calls:[{name,args:{}}]}:name==='click'?{calls:[{name,args:{observationId:o.id,elementRef:o.elements.find(e=>e.name==='删除账户')!.ref}}]}:{calls:[{name,args:{url:'https://example.com/'}}]});const before=(await getActions()).length;const run=await start();if(name==='delete_database'){assert.equal((await terminal(run.id)).run.errorCode,'UNKNOWN_TOOL');}else{await until(async()=>(await get(run.id)).steps.some(s=>s.errorCode==='POLICY_BLOCKED'),'policy');await fetch(`${base}/sessions/${session.id}/agent-runs/${run.id}/stop`,{method:'POST'});}assert.equal((await getActions()).length,before);}
    fake.reset(()=>({calls:[{name:'type_text',args:{observationId:123,elementRef:null,text:'invalid'}}]}));assert.equal((await terminal((await start()).id)).run.errorCode,'TOOL_VALIDATION_ERROR');
  });
  await t.test('takeover aborts model, Human blocks start, explicit resume',async()=>{
    fake.reset(()=>({delayMs:2000,calls:[{name:'wait',args:{ms:500}}]}));const r=await start();await until(()=>fake.requests.length===1,'model pending');const before=(await getActions()).length;const at=Date.now();stream.socket.send(JSON.stringify({type:'control-acquire',sessionId:session.id}));await until(async()=>(await get(r.id)).run.status==='paused_by_human','paused',1000);assert.ok(Date.now()-at<1000);
    await until(()=>stream.messages.some(m=>m.type==='control-state'&&m.heldBySelf),'Human lease');const lease=[...stream.messages].reverse().find(m=>m.type==='control-state'&&m.heldBySelf);assert.ok(lease?.type==='control-state'&&lease.leaseId);
    await until(()=>fake.aborted>0,'provider aborted');stream.socket.send(JSON.stringify({type:'control-release',sessionId:session.id,leaseId:lease.leaseId}));await delay(150);assert.equal((await get(r.id)).run.status,'paused_by_human');assert.equal((await getActions()).length,before);
    fake.reset(happy);const response=await fetch(`${base}/sessions/${session.id}/agent-runs/${r.id}/resume`,{method:'POST'});assert.equal(response.status,200);assert.equal((await terminal(r.id)).run.status,'completed');
  });
  await t.test('typed text absent from metadata logs and sanitized DOM',async()=>{
    const secret=`REPROPATH_AGENT_SECRET_${randomUUID()}`;fake.reset((o,i)=>i===0?{calls:[{name:'type_text',args:{observationId:o.id,elementRef:o.elements.find(e=>e.name==='普通输入')!.ref,text:secret}}]}:{calls:[{name:'finish',args:{summary:'输入已完成'}}]});const r=await terminal((await start()).id);assert.equal(r.run.status,'completed');const actions=await getActions();assert.doesNotMatch(JSON.stringify([r,actions,stream.events]),new RegExp(secret));
    for(const a of actions.filter(a=>a.kind==='type'))for(const p of [a.before,a.after]){assert.ok(p?.dom);assert.doesNotMatch(await(await fetch(`${base}/artifacts/${p.dom.id}`)).text(),new RegExp(secret));}
    assert.doesNotMatch(host.logs()+control.logs()+worker.logs(),new RegExp(secret+'|FIXTURE_AGENT_API_KEY'));
  });
  await t.test('20 step budget with bounded model context',async()=>{fake.reset(()=>({calls:[{name:'observe_page',args:{}}]}));const r=await terminal((await start()).id);assert.equal(r.run.finishReason,'budget_exhausted');assert.equal(r.run.stepCount,20);assert.equal(fake.requests.length,20);assert.ok(Math.max(...fake.requests.map(r=>r.messages.length))<=2);const c=JSON.parse(fake.requests.at(-1)!.messages.at(-1)!.content);assert.ok(c.recent.length<=5);assert.ok(JSON.stringify(c).length<26000);});
  await t.test('stale result reaches model and recovers',async()=>{let old='';fake.reset((o,i)=>{if(i===0){old=o.id;return {calls:[{name:'observe_page',args:{}}]};}if(i<3)return {calls:[{name:'click',args:{observationId:i===1?old:o.id,elementRef:o.elements.find(e=>e.name==='Login')!.ref}}]};return {calls:[{name:'finish',args:{summary:'恢复成功'}}]};});const r=await terminal((await start()).id);assert.equal(r.run.status,'completed');assert.ok(r.steps.some(s=>s.errorCode==='STALE_OBSERVATION'));assert.match(JSON.stringify(fake.requests[2]),/STALE_OBSERVATION/);});
  await t.test('same-origin navigation, go_back, key and scroll use recorded path',async()=>{fake.reset((_o,i)=>({calls:[i===0?{name:'navigate',args:{url:`${base}/test-page/agent?next=1#fragment`}}:i===1?{name:'go_back',args:{}}:i===2?{name:'press_key',args:{key:'Tab',modifiers:[]}}:i===3?{name:'scroll',args:{deltaX:0,deltaY:100}}:{name:'finish',args:{summary:'导航与输入完成'}}]}));const before=(await getActions()).length;const r=await terminal((await start()).id);assert.equal(r.run.status,'completed');assert.deepEqual((await getActions()).slice(before).map(a=>a.kind),['navigation','navigation','key','scroll']);});
  await t.test('Human-owned blocks model; duplicate active run and Stop',async()=>{
    stream.socket.send(JSON.stringify({type:'control-acquire',sessionId:session.id}));await until(()=>stream.messages.at(-1)?.type==='control-state'&&stream.messages.at(-1)?.type==='control-state','state');await delay(100);fake.reset();const count=fake.requests.length;
    let response=await fetch(`${base}/sessions/${session.id}/agent-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:'blocked'})});assert.equal((await response.json()).error,'CONTROL_BUSY');assert.equal(fake.requests.length,count);
    const lease=[...stream.messages].reverse().find(m=>m.type==='control-state'&&m.heldBySelf);assert.ok(lease?.type==='control-state');stream.socket.send(JSON.stringify({type:'control-release',sessionId:session.id,leaseId:lease.leaseId}));await delay(100);
    fake.reset(()=>({delayMs:2000,text:'pending'}));const r=await start();await until(()=>fake.requests.length===1,'model pending');response=await fetch(`${base}/sessions/${session.id}/agent-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:'duplicate'})});assert.equal((await response.json()).error,'AGENT_ALREADY_RUNNING');
    await fetch(`${base}/sessions/${session.id}/agent-runs/${r.id}/stop`,{method:'POST'});assert.equal((await get(r.id)).run.finishReason,'stopped_by_user');assert.equal((await get(r.id)).run.status,'stopped');assert.equal(stream.states.at(-1)?.status,'running');
  });
  await t.test('Agent Host crash releases control; unavailable and restart',async()=>{
    fake.reset(()=>({delayMs:2000,text:'pending'}));const r=await start();await until(()=>fake.requests.length===1,'pending model');host.child.kill();await until(async()=>(await get(r.id)).run.status==='failed','host failed');assert.equal(stream.states.at(-1)?.status,'running');
    const response=await fetch(`${base}/sessions/${session.id}/agent-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:'host down'})});assert.equal((await response.json()).error,'AGENT_HOST_UNAVAILABLE');
    host=service('apps/agent-host/src/index.ts',{AGENT_HOST_PORT:String(ap),AGENT_CONTROL_URL:`ws://127.0.0.1:${cp}/agent-host`,REPROPATH_AGENT_BASE_URL:modelURL,REPROPATH_AGENT_API_KEY:'FIXTURE_AGENT_API_KEY',REPROPATH_AGENT_MODEL:'fixture'});await until(async()=>((await(await fetch(`${base}/health`)).json()) as {modelAvailable:boolean}).modelAvailable,'host restart');fake.reset(happy);assert.equal((await terminal((await start()).id)).run.status,'completed');
  });
  await t.test('bounded retention and REST lifecycle validation',async()=>{for(let i=0;i<21;i++){fake.reset(()=>({calls:[{name:'finish',args:{summary:'完成'}}]}));await terminal((await start()).id);}const records=await(await fetch(`${base}/sessions/${session.id}/agent-runs`)).json();assert.equal(records.length,20);assert.ok(records.every((r:{steps:AgentStep[]})=>r.steps.length<=20));assert.equal((await fetch(`${base}/sessions/${session.id}/agent-runs/missing`)).status,404);assert.equal((await fetch(`${base}/sessions/${session.id}/agent-runs/${records[0].run.id}/resume`,{method:'POST'})).status,409);});
  await t.test('Session close terminates Agent and preserves artifacts',async()=>{fake.reset(()=>({delayMs:2000,text:'pending'}));const r=await start();await until(()=>fake.requests.length===1,'model wait');await fetch(`${base}/sessions/${session.id}`,{method:'DELETE'});assert.equal((await get(r.id)).run.finishReason,'session_ended');await until(()=>stream.states.at(-1)?.status==='closed','closed');const actions=await getActions();assert.ok(actions.length>0);assert.equal((await fetch(`${base}/artifacts/${actions[0]!.before!.screenshot!.id}`)).status,200);});
});
