import test from 'node:test';
import assert from 'node:assert/strict';
import { create,freePort,ready,service,subscribe,until } from './helpers.js';
import { AgentFakeModel } from './agent-model.js';
import { setTimeout as delay } from 'node:timers/promises';
test('Agent unavailable, timeout, delayed Worker fence, Worker loss', {timeout:60000},async t=>{
  const wp=await freePort(),cp=await freePort(),ap=await freePort();const base=`http://127.0.0.1:${cp}`,hostURL=`ws://127.0.0.1:${cp}/agent-host`;const fake=new AgentFakeModel();const modelURL=await fake.start();
  const worker=service('apps/browser-worker/src/index.ts',{WORKER_PORT:String(wp),NODE_ENV:'test',REPROPATH_TEST_AGENT_DELAY_MS:'500',REPROPATH_AUTH_FILE:''});
  const control=service('apps/control/src/index.ts',{CONTROL_PORT:String(cp),WORKER_URL:`ws://127.0.0.1:${wp}/worker`,NODE_ENV:'test',REPROPATH_TEST_AGENT_RUNTIME_MS:'1000'});
  let host:ReturnType<typeof service>|undefined;t.after(async()=>{await host?.stop();await control.stop();await worker.stop();await fake.close();});await ready(base,true);
  const session=await create(base,`${base}/test-page/agent`);const stream=await subscribe(base,session.id);t.after(()=>stream.socket.close());await until(()=>stream.states.at(-1)?.status==='running','browser ready');
  const start=async()=>{const r=await fetch(`${base}/sessions/${session.id}/agent-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:'检查'})});return {status:r.status,data:await r.json()};};
  const get=async(id:string)=>await(await fetch(`${base}/sessions/${session.id}/agent-runs/${id}`)).json();
  await t.test('absent Host leaves Human/browser usable',async()=>{assert.equal((await start()).data.error,'AGENT_HOST_UNAVAILABLE');assert.equal(stream.states.at(-1)?.status,'running');await until(()=>stream.frames.length>0,'live frames without Host');});
  await t.test('healthy Host without model configuration',async()=>{host=service('apps/agent-host/src/index.ts',{AGENT_HOST_PORT:String(ap),AGENT_CONTROL_URL:hostURL,REPROPATH_AGENT_BASE_URL:'',REPROPATH_AGENT_API_KEY:'',REPROPATH_AGENT_MODEL:''});await ready(`http://127.0.0.1:${ap}`);await until(async()=>(await(await fetch(`${base}/health`)).json()).agentHostConnected,'connected');assert.equal((await start()).data.error,'AGENT_MODEL_UNAVAILABLE');assert.equal((await(await fetch(`http://127.0.0.1:${ap}/health`)).json()).modelAvailable,false);await host.stop();});
  host=service('apps/agent-host/src/index.ts',{AGENT_HOST_PORT:String(ap),AGENT_CONTROL_URL:hostURL,REPROPATH_AGENT_BASE_URL:modelURL,REPROPATH_AGENT_API_KEY:'fixture',REPROPATH_AGENT_MODEL:'fixture'});await until(async()=>(await(await fetch(`${base}/health`)).json()).modelAvailable,'model available');
  await t.test('Control watchdog timeout aborts model and releases authority',async()=>{fake.reset(()=>({delayMs:2000,text:'late'}));const {data}=await start();await until(async()=>(await get(data.id)).run.status==='failed','timeout');assert.equal((await get(data.id)).run.finishReason,'run_timeout');await until(()=>fake.aborted>0,'aborted');assert.equal((await(await fetch(`${base}/sessions/${session.id}/actions`)).json()).length,0);});
  await t.test('takeover before delayed mutation creates no Action',async()=>{
    fake.reset(o=>({calls:[{name:'click',args:{observationId:o.id,elementRef:o.elements.find(e=>e.name==='Login')!.ref}}]}));const {data}=await start();await until(()=>fake.requests.length===1,'model selected click');await delay(100);const begin=Date.now();stream.socket.send(JSON.stringify({type:'control-acquire',sessionId:session.id}));await until(async()=>(await get(data.id)).run.status==='paused_by_human','paused');assert.ok(Date.now()-begin<1000);await delay(650);assert.equal((await(await fetch(`${base}/sessions/${session.id}/actions`)).json()).length,0);assert.equal(stream.events.filter(e=>e.type==='request'&&e.payload.url.endsWith('/fixture/agent/login')).length,0);
    const lease=[...stream.messages].reverse().find(m=>m.type==='control-state'&&m.heldBySelf);assert.ok(lease?.type==='control-state');stream.socket.send(JSON.stringify({type:'control-release',sessionId:session.id,leaseId:lease.leaseId}));await fetch(`${base}/sessions/${session.id}/agent-runs/${data.id}/stop`,{method:'POST'});await delay(50);
  });
  await t.test('Worker loss terminates Run; Control and Agent Host survive',async()=>{fake.reset(()=>({delayMs:2000,text:'late'}));const {data}=await start();await until(()=>fake.requests.length===1,'model waiting');worker.child.kill();await until(()=>stream.states.at(-1)?.status==='failed','session failed');assert.ok(['stopped','failed'].includes((await get(data.id)).run.status));assert.equal((await fetch(`${base}/health`)).status,200);assert.equal((await fetch(`http://127.0.0.1:${ap}/health`)).status,200);});
});
